### PR TITLE
Make ILogger covariant

### PR DESCRIPTION
**Pull request by anpete**

### CODE REVIEW

**Comment by Eilon** [comment]
@lodejard FYI. This seems fine to me.

**Comment by Eilon** [comment]
Just curious what the reason for this is in terms of scenario? I don't see any problem with this change - just wondering what code would be unblocked with this.

**Comment by anpete** [comment]
```c#
public class Base
{
    private readonly ILogger<Base> _logger;

    public Base(ILogger<Base> logger)
    {
        _logger = logger;
    }
}

private class Derived : Base
{
    public Derived(ILogger<Derived> logger)
        : base(logger)
    {
                
    }
}
```

**Comment by Eilon** [comment]
Ah, cool, so I think for that code you want it to be covariant, right? :smile: 

:shipit:

**Comment by anpete** [comment]
That's what I said :smile:

**Comment by Eilon** [comment]
:trollface:

**Comment by anpete** [comment]
:expressionless:

**Pull request merged**
