### PR TITLE
Remove ReflectionBasedLogValues type

### PR DESCRIPTION
**Pull request by kichalla**
Fixes issue : https://github.com/aspnet/Logging/issues/171

The original(if you look at the renaming of the title for the above issue) issue mentioned about moving this type to an assembly which does not depend on DependencyInjection.

The type [FormattedLogValues](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Framework.Logging.Abstractions/Internal/FormattedLogValues.cs) is actually part of Logging.Abstractions and does not have dependency on DependencyInjection.

Also I checked that ReflectionBasedLogValues is not being used in any other repos.
https://github.com/search?utf8=%E2%9C%93&q=user%3Aaspnet+ReflectionBasedLogValues&type=Code&ref=searchresults

/cc: @muratg @Eilon

### CODE REVIEW

**Comment by muratg** [comment]
@kichalla is `ReflectionBasedLogValues` used in other repos? If so, you'll need to change those similar to the tests. Building Universe with this change would find most of them (but probably not all.)

**Comment by muratg** [comment]
If all good, :shipit:

**Comment by kichalla** [comment]
@muratg No, it's not being used in any other repos : https://github.com/search?utf8=%E2%9C%93&q=user%3Aaspnet+ReflectionBasedLogValues&type=Code&ref=searchresults

**Comment by Eilon** [comment]
:shipit:

**Pull request merged**
