### PR TITLE
Don't reference design-time facades on net451

### PR DESCRIPTION
**Pull request by bricelam**
Without this, the packages won't install into "classic" Full .NET projects

### CODE REVIEW

**Comment by Eilon** [comment]
@davidfowl ?

**Comment by davidfowl** [comment]
I think we should make these all as build dependencies so that DNX still works for now

**Comment by Eilon** [comment]
@davidfowl that sounds like a :shipit: to me?

**Comment by bricelam** [comment]
I don't think the two I removed were even used. There's nothing portable in the dependency closure. Concurrent types live in System and mscorlib on Full .NET.

**Comment by davidfowl** [comment]
:shipit:

**Comment by Eilon** [comment]
@bricelam I logged https://github.com/aspnet/DnxTools/issues/30, assigned to you.

**Pull request merged**
