### PR TITLE
Console Logger Settings should not have to respect Enum case

### PR DESCRIPTION
**Pull request by ORuban**
See https://github.com/aspnet/Logging/issues/381

### CODE REVIEW

**Comment by davidfowl** [comment]
Add a test.

**Comment by DoCode** [comment]
@ORuban, please can you add a test, that this PR can merged?
/cc @davidfowl

**Comment by muratg** [comment]
@BrennanConroy Can you add a test before merging?

**Comment by muratg** [comment]
@BrennanConroy Could you add the test from https://github.com/aspnet/Logging/pull/460 to this one?

**Comment by BrennanConroy** [comment]
Thank you @ORuban and @Yves57 23c2930b90754871521fa536ebcf3c6abc90049e 9a35b4a5581e940100dca944ae3afd6f70b37614

**Pull request closed without merging**
