### PR TITLE
Target .NET Standard 2.0

### PR DESCRIPTION
**Pull request by natemcmaster**
Part of aspnet/Home#2045

### CODE REVIEW

**Comment by BrennanConroy** [comment]
dev or preview2?

**Comment by natemcmaster** [comment]
dev

**Comment by BrennanConroy** [comment]
Shouldn't there be new baselines to replace the ones you deleted?

**Comment by natemcmaster** [comment]
They already exist. Baseline.netcore.json. I've just deleted the duplicates.

**Pull request merged**
