### PR TITLE
Adding appveyor.yml

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by PureKrome** [comment]
@pranavkm Is the appveyor `aspnet/logging` project, public? (ie. can we access it)?

**Comment by pranavkm** [comment]
https://ci.appveyor.com/project/aspnetci/Logging. Working on adding build status badges (see https://github.com/aspnet/Mvc) to all the repos

**Comment by PureKrome** [comment]
Heh :) that's what i was going to PR :) May I ? (i've done it before for my OSS)

**Comment by pranavkm** [comment]
Sure - also add the Travis one while you're at it. The Mvc and dnx ones have the root project name.

**Comment by PureKrome** [comment]
woot

i'll do it on my lunch break in an hour or so :+1:

**Pull request closed without merging**
