### PR TITLE
Switched URL to elmah.io extensions logger

### PR DESCRIPTION
**Pull request by ThomasArdal**
We've created a new logger for elmah.io based on .NET Core.

### CODE REVIEW

**Comment by ThomasArdal** [comment]
Seems like there's an existing problem with the continuous build. This PR contains markdown changes only :smile:

**Comment by 304NotModified** [comment]
To bad it isn't .Extensions.Logging like the others

**Comment by ThomasArdal** [comment]
@304NotModified Very interested in hearing your throughs on why? The AspNetCore package contains everything to support ASP.NET Core. We could split it into Elmah.Io.Extensions.Logging and make Elmah.Io.AspNetCore dependent of that, but I think that it would confuse people and open up for dll-dependency-hell :smile:

**Comment by ThomasArdal** [comment]
@304NotModified Now you got me all in doubt :smiley:. Having two NuGet packages could make sense. If you "just" want to use [elmah.io](https://elmah.io) as a logging framework for ASP.NET Logging, you could use Elmah.Io.Extensions.Logging and if you wan't the full "ELMAH" experience, you would install Elmah.Io.AspNetCore (as well as Elmah.Io.Extensions.Logging).

**Comment by 304NotModified** [comment]
yes, we (NLog) have also two packages, NLog.Extensions.Logging & NLog.Web.AspNetCore (And NLog of course)

The confusing part is that Microsoft.Extensions.Logging isn't only for ASP.NET Core (but also .NET Core without ASP)

**Comment by ThomasArdal** [comment]
Now I understand. The aspnet/Logging had me confused as well. If ASP.NET Logging is in fact .NET Core logging, Elmah.Io.Extensions.Logging makes total sense. Will start working on that. Thx!

**Comment by ThomasArdal** [comment]
@304NotModified There's an [Elmah.Io.Extensions.Logging](https://github.com/elmahio/Elmah.Io.Extensions.Logging) now. Thanks for your input.

**Comment by davidfowl** [comment]
@ThomasArdal 😄

**Pull request merged**
