### PR TITLE
Making LoggingEventSource public sealed

### PR DESCRIPTION
**Pull request by rymeskar**
Fixing [#899](https://github.com/aspnet/Logging/issues/899)

### CODE REVIEW

**Comment by rymeskar** [comment]
The check failures do not seem to be related to my changes. Unfortunately, I am not able to rerun them without a new commit :(

**Comment by pakrym** [comment]
Not sure we want to expose Keywords in this manner. I was thinking about moving the enum out of the class and exposing only it.

**Comment by rymeskar** [comment]
When I read [this blog post ](https://blogs.msdn.microsoft.com/vancem/2012/08/14/etw-in-c-controlling-which-events-get-logged-in-an-system-diagnostics-tracing-eventsource/) from 2012.
It mentioned that the Keywords must be nested.

But TBH, I am not sure what is the enforcement mechanism or whether that requirement still holds.

**Comment by pakrym** [comment]
Good point.

Make sure every other member is private/internal then.

**Comment by pakrym** [comment]
Thank you for your contribution.

**Pull request merged**
