### PR TITLE
Add extension to have CreateLogger with Type object as well as generic

### PR DESCRIPTION
**Pull request by adamhathcock**
Sometimes I'm dealing with a Type object when hooking up the MF.Logging shim to other logging shims.

### CODE REVIEW

**Comment by adamhathcock** [comment]
Updated this.

**Comment by muratg** [comment]
@kichalla Could you take this one in?

**Comment by muratg** [comment]
:watch:

**Comment by kichalla** [comment]
3cecf9e011c2cc94354e3f39f946a71a6282e21c

Thanks! @adamhathcock

**Pull request closed without merging**
