### PR TITLE
Don't double quote AssemblyTestLog parameters

### PR DESCRIPTION
**Pull request by halter73**
See https://github.com/serilog/serilog/issues/956

### CODE REVIEW

**Comment by JunTaoLuo** [comment]
Is this what broke some of our tests?

**Comment by halter73** [comment]
I doubt this is what broke our tests. The double quoting was just annoying me.

**Comment by BrennanConroy** [comment]
Besides notifying Eilon, I think you need to update universe too. https://github.com/aspnet/Universe/blob/release/2.2/build/dependencies.props#L119

**Comment by Eilon** [comment]
Sorry I'm not sure I understood - what's the ultimate motivation of updating the dependency? Is it due to test failures? Or just to help users get the latest Serilog? To fix a bug?

**Comment by JunTaoLuo** [comment]
I think this is just for aesthetics and the double quotes were annoying @halter73.

**Comment by Eilon** [comment]
That's a pretty weak-sauce argument 😄 Are there any other reasons to update? We do like to keep things fresh, but this is also a major version update of a dependency, so are there any Serilog breaking changes that we would be forcing users to deal with?

**Comment by JunTaoLuo** [comment]
I didn't know we needed a version update when I originally reviewed the PR but as mentioned above, this package is only used in noship packages and test projects so I think updating the version is okay as long as all of our tests continue pass.

**Comment by Eilon** [comment]
Oh it's not in anything we ship? I'll gladly approve that then, if someone can confirm that.

**Pull request merged**
