### PR TITLE
Fix unix Console colors

### PR DESCRIPTION
**Pull request by BrennanConroy**
#417 
@davidfowl @kichalla @muratg 
screen shot 2016-05-20 at 9 40 50 am

### CODE REVIEW

**Comment by kichalla** [comment]
`fail` is hard to read. 

:shipit:

**Comment by BrennanConroy** [comment]
Agreed, which is why I got a screen shot. Should we do something about it?

**Comment by muratg** [comment]
@BrennanConroy What are the other possible colors we can put instead of red? 

Also, did you try both types of reds?

**Comment by BrennanConroy** [comment]
We decided to change fail to red background, black text

**Comment by JunTaoLuo** [comment]
@BrennanConroy update screenshot? Also doesn't that make `crit` and `fail` look almost identical? Is there an orange color that may work better?

**Comment by BrennanConroy** [comment]
Possible colors are in this color table https://en.wikipedia.org/wiki/ANSI_escape_code#Colors

**Comment by BrennanConroy** [comment]
screen shot 2016-05-23 at 9 16 46 am

**Comment by JunTaoLuo** [comment]
:shipit:

**Comment by davidfowl** [comment]
:shipit:

**Pull request merged**
