### PR TITLE
Snazzify the Console Output and move the extension methods to Interfaces

### LINKED ISSUE #119: API review: LoggerExtensions changes
- Move to Interfaces assembly
- Rename Write* methods to Log* (This is a big change across repos)

### PR DESCRIPTION
**Pull request by anurse**
This is a pre-req for aspnet/XRE#1314 that pulls logging in to the core runtime. It doesn't fully fix #119, but it does the first half by pulling the Extension methods over to the Interfaces assembly. I don't have the cycles to do the rename part :(.

@davidfowl suggested a minor tidy up of Console Logger if we're going to use it in the runtime:

capture

/cc @BrennanConroy @davidfowl @muratg

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@anurse__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <p>
        It looks like you're a Microsoft contributor (Andrew Stanton-Nurse). If you're full-time, we DON'T require a Contribution License Agreement. If you are a vendor, please DO sign the electronic Contribution License Agreement. It will take 2 minutes and there's no faxing! https://cla2.msopentech.com.
    </p>

TTYL, MSOTBOT;

**Comment by BrennanConroy** [comment]
You don't need the NotNull file anymore, use Microsoft.Framework.Internal

**Comment by anurse** [comment]
:+1: removed!

**Comment by davidfowl** [comment]
:shipit:

**Comment by Eilon** [comment]
yes :shipit: very nice!

**Pull request merged**
