### PR TITLE
fix some mistakes.

### PR DESCRIPTION
**Pull request by wenhx**

### CODE REVIEW

**Comment by Eilon** [comment]
Hi, nice finds! Can you please fill out a Contributor License Agreement as described in the contributions guidelines? Thanks! https://github.com/aspnet/Home/blob/master/CONTRIBUTING.md

**Comment by wenhx** [comment]
OK, I will sign a Contributor License Agreement.
I got a error when i submit the request form, I had contact the public email on the web page(https://cla.msopentech.com/).
And i will try again later.

**Comment by wenhx** [comment]
Hi @Eilon , I had signed the Contributor License Agreement.

**Comment by Eilon** [comment]
CLA confirmed.

@Tratcher can you review and merge?

**Pull request merged**
