### PR TITLE
Print exception not just message

### PR DESCRIPTION
**Pull request by BrennanConroy**
#355 
@moozzyk @lodejard

### CODE REVIEW

**Comment by davidfowl** [comment]
screnshot?

**Comment by BrennanConroy** [comment]
ex

**Comment by lodejard** [comment]
I guess if Exception.ToString is always going to show the full type, then showing the exception type in its own line is redundant. Also if the call stack is indented there's no reason to indent the exception itself. the stack frame indentation should provide the visual break to the next line.

**Comment by BrennanConroy** [comment]
ex

**Comment by BrennanConroy** [comment]
Ping @davidfowl @lodejard

**Comment by muratg** [comment]
:eyes: :watch:

**Comment by lodejard** [comment]
:rotating_light: :moneybag: :ok_hand: :shipit: :smile_cat:

**Pull request merged**
