### PR TITLE
Move interfaces into their own package.

### PR DESCRIPTION
**Pull request by ejsmith**
This is a small change and should not affect any of the projects using this library, but it could have a huge impact on the logging fragmentation on .NET. If we can get everyone to agree on these very simple interfaces ILogger and ILoggerFactory then we can avoid the hell of having to create a bunch of proxies that translate between the various logging frameworks.

### CODE REVIEW

**Comment by olepichon-systran** [comment]
I know about https://github.com/aspnet/dnx/issues/2003 but this kind of interfaces would have been great candidates for AssemblyNeutral usage.

**Comment by MuiBienCarlota** [comment]
I know about aspnet/dnx#2003 but this kind of interfaces would have been great candidates for AssemblyNeutral usage.

**Comment by ejsmith** [comment]
Yeah, absolutely. Bummer that they got cut.

**Comment by 304NotModified** [comment]
@ejsmith is this for https://github.com/aspnet/Logging/issues/370?

**Comment by ejsmith** [comment]
Yes it is

**Comment by muratg** [comment]
We won't be making this change as it's a big breaking change.

**Pull request closed without merging**
