### PR TITLE
Use TypeNameHelper from aspnet/Common repo

### LINKED ISSUE #175: Incorrect DisplayName from TypeNameHelper
The present implementation of TypeNameHelper gives wrong display name for nested classes if the outer class is generic.
````C#
public class A<T>
{
    public class B<T2> { }
}

Console.Writeline(TypeNameHelper.GetTypeDisplayFullName(typeof(A<int>.B<string>))
// output should be
// namespace.A<System.Int32>+B<System.String>
// Current output
// namespace.A<System.Int32, System.String>
````
aspnet/common#15 adds TypeNameHelper with correction of above bug. Once the pull request merged, make use of common repo for Logging.

### PR DESCRIPTION
**Pull request by smitpatel**
Resolves #175

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@smitpatel__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <p>
        It looks like you're a Microsoft contributor (Smit Patel). If you're full-time, we DON'T require a Contribution License Agreement. If you are a vendor, please DO sign the electronic Contribution License Agreement. It will take 2 minutes and there's no faxing! https://cla2.msopentech.com.
    </p>

TTYL, MSOTBOT;

**Comment by smitpatel** [comment]
@bricelam

**Comment by Eilon** [comment]
I love seeing lots of code get deleted :smile: 

:shipit:

**Comment by avanderhoorn** [comment]
Will packages like `Microsoft.Framework.TypeNameHelper.Internal` are they going to be "unlisted" on nuget?

**Comment by bricelam** [comment]
@avanderhoorn They're kind of like universal projects--they don't produce a package; they're just a convenient way of sharing source files between different projects.

**Comment by avanderhoorn** [comment]
Is that what the `"type": "build",` does? Is it kinda like a source package?

**Comment by Eilon** [comment]
@avanderhoorn not kinda, but exactly :smile:

**Comment by avanderhoorn** [comment]
Great! Given that, if its not in Nuget how would we reference this package if we want to use it?

**Comment by Eilon** [comment]
It's currently meant just as a shortcut for us as opposed to being externally consumable code.

**Pull request merged**
