### PR TITLE
Make logging more "pay-for-play" by avoiding unnecessary allocations

### PR DESCRIPTION
**Pull request by justinvp**
This is an initial PR that demonstrates the changes as discussed in #100. This PR currently only includes changes for `LogLevel.Verbose` -- the remaining levels will be added, along with tests, if/when the owners are on board with such improvements.

### CODE REVIEW

**Comment by muratg** [comment]
@davidfowl does this look good to you?  I believe Justin may do the other levels if the approach is right. Perf improvements seem pretty good.

**Comment by davidfowl** [comment]
Hey @justinvp, we made a bunch of changes to the logging APIs, it looks like these changes might not make such a big difference anymore but we should measure and confirm. There seems to be 2 general changes here:

- Avoid boxing if the log level isn't enabled
- Avoid string.Format

It might be worthwhile adding generic overloads if we realize that boxing is a huge cost but with the latest design, nothing should be formatted until the logger provider actually decides to log for that level. The overloads that used to format now allocate FormatLogValues object (https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Framework.Logging.Abstractions/Internal/FormattedLogValues.cs#L13) which is only realized if the underlying logger decides it needs to log.

**Comment by justinvp** [comment]
@davidfowl, the logging APIs, as currently implemented, are still allocation-heavy, even when the log level isn't enabled.

Consider the [following](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Framework.Logging.Abstractions/LoggerExtensions.cs#L46-L49):

```c#
public static void LogDebug([NotNull] this ILogger logger, string format, params object[] args)
{
    logger.Log(LogLevel.Debug, 0, new FormattedLogValues(format, args), null, MessageFormatter);
}
```

Allocations on each call to `LogDebug` (even when the log level isn't enabled):

 1. new params array
 2. boxing (for each arg that is a value type)
 3. new `FormattedLogValues`
 4. new `Func<object, Exception, string>` (for `MessageFormatter`)

The `Func` delegate allocation (4) can be trivially addressed by using a single cached `Func` instance. I've submitted a new PR for this, #193.

The `FormattedLogValues` allocation (3) can be avoided by checking `IsEnabled` before allocating it and calling the log method.

The params array allocation (1) can be avoided for a common number of arguments (typically three) with overloads.

The boxing allocations (2) can be avoided with generic overloads.

I'll update the PR to address 1-3 and measure to see.

**Comment by Eilon** [comment]
@justinvp BTW our recommended logging pattern is for anyone concerned about perf to always check if logging is enabled for a particular level, and to only then do the logging.

**Comment by muratg** [comment]
@justinvp Are you still looking at the changes here (in particular 1-3 above) and the measurements? Or should we close this one?

**Comment by muratg** [comment]
@justinvp Let me know if you come back to this, and we can re-open the discussion/PR.  Thanks.

**Pull request closed without merging**
