### PR TITLE
Add Exception to DebugLogger output

### PR DESCRIPTION
**Pull request by ORuban**

### CODE REVIEW

**Comment by BrennanConroy** [comment]
Could you rebase on latest and I'll merge

**Comment by ORuban** [comment]
updated

**Comment by BrennanConroy** [comment]
Squash please :)

**Comment by 304NotModified** [comment]
Some bit off topic: Is this really the correct way to log an exception?

**Comment by ORuban** [comment]
@BrennanConroy squashed

**Comment by BrennanConroy** [comment]
Thanks!

**Pull request merged**
