### PR TITLE
Set background color with foreground color in ConsoleLogger 

### PR DESCRIPTION
**Pull request by BrennanConroy**
#378

### CODE REVIEW

**Comment by Eilon** [comment]
:shipit:

**Comment by davidfowl** [comment]
Screenshot on osx? :smile:

**Comment by Eilon** [comment]
@davidfowl it looks like a clown ate a unicorn :smile:

**Comment by davidfowl** [comment]
Is it going to put a black background on my white console with white text?

**Comment by BrennanConroy** [comment]
It's going to use your default colors for everything except the log level text, logger name, and eventid

Sent from my HTC

----- Reply message -----

**Comment by Eilon** [comment]
Yeah the colorization is only for the "header" of each log entry, for which we explicitly set both background and foreground color (to ensure good contrast). Then the log details are in whatever color you had in your console.

**Pull request merged**
