### PR TITLE
Cache the console log scope path if its already calculated

### PR DESCRIPTION
**Pull request by kichalla**
@rynowak

### CODE REVIEW

**Comment by rynowak** [comment]
What's the purpose of this change?

**Comment by kichalla** [comment]
@rynowak The current implementation is inefficient as we repeatedly calculate it for every log message written. BTW we already have tests covering the scope path scenarios so this change is safe.

**Comment by rynowak** [comment]
Why is this closed?

Get some perf data, ping me if you need help measuring

**Comment by 304NotModified** [comment]
I don't like micro optimalisations, but doing expensive stuff for every log message sounds wrong. So I think this is a good PR.

**Pull request closed without merging**
