### PR TITLE
Initial prototype of Windows Event Log logger

### PR DESCRIPTION
**Pull request by JesperTreetop**
As requested by @davidfowl for use in issue #83. Built using Visual Studio 2015 CTP 6.

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@JesperTreetop__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla2.msopentech.com.
    </span>

TTYL, MSOTBOT;

**Comment by msotclas** [comment]
__@JesperTreetop__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, MSOTBOT;

**Comment by muratg** [comment]
@JesperTreetop Thanks for the PR. Have you seen @davidfowl's last comment on https://github.com/aspnet/Logging/issues/83?

**Comment by JesperTreetop** [comment]
@muratg Yep. This is not finished work and I do not have time to finish it myself - however, I was asked to contribute what I had regardless and so I did. Maybe a pull request is the wrong form since I don't expect it to be absorbed as is. I am assuming any comments are meant for future reference or for the continued discussion in that thread.

**Comment by muratg** [comment]
@JesperTreetop Got it, thanks!

**Comment by kichalla** [comment]
Closing this as we have a new PR for this https://github.com/aspnet/Logging/pull/225

**Comment by JesperTreetop** [comment]
Good to see this moving forward :+1:

**Pull request closed without merging**
