### PR TITLE
:sparkling_heart: Added badges!

### PR DESCRIPTION
**Pull request by PureKrome**
- NuGet badges.
- AppVeyor badge.
- Travis badge.

NOTE! Badges reference the dev branches.

Reference: #161

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@PureKrome__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, MSOTBOT;

**Comment by pranavkm** [comment]
cc @Eilon - https://github.com/PureKrome/Logging/tree/badges for OKing the aesthetics of the result

**Comment by PureKrome** [comment]
@Eilon - the main aesthetic difference is the fact that I added 2x NuGet badges ... where other repo's (if they have any badges) don't have that one. So the (indirect) suggestion by me, is to add the NuGet ones to the other repo's too (yeah - more work, though).

**Comment by Eilon** [comment]
I wonder if it's best to point to NuGet or to instead point to the MyGet AspNetVNext feed?

**Comment by PureKrome** [comment]
The ASPNET _Home_ repo has both `master` and `dev` branche, badges. These both direct to `myget` though.

Maybe we can offer a similar thing. For example: -
Master: <NuGet badge>
Dev: <MyGet badge> <-- not sure what branch, though.

**Comment by Eilon** [comment]
Yeah that might be better. For the `dev` branch on GitHub, the feed is `aspnetvnext`.

**Comment by PureKrome** [comment]
>For the dev branch on GitHub

I'm guessing you ment to say: _For the `dev` branch on **MyGet**_ .. because I couldn't find anything on GH. As such, i've pointed the `dev` package to the MyGet feed .. specifically at `Microsoft.Framework.Logging` package.

I've updated my fork and this is what it's now looking like:

image

Even though my fork+branch is updated, it doesn't look like it's propagated through this PR .. which should happen automatically... ??

**Comment by Eilon** [comment]
Yeah I don't see your changes in the PRs. Did you push to the origin? Or worst case, just close this PR and send a new one.

**Comment by PureKrome** [comment]
>Did you push to the origin?

Yep, sure did. I even got @pranavkm to check (cause I thought I'm going crazy) and he said he see's it there but is also confused why it didn't refresh, here.

>just close this PR and send a new one.  

I'll do that right now and reference this (to be closed) PR.

**Pull request closed without merging**
