### PR TITLE
Remove portable target

### PR DESCRIPTION
**Pull request by bricelam**
Given the removal of ANIs, this isn't needed anymore

### CODE REVIEW

**Comment by BrennanConroy** [comment]
Remove [Runtime.AssemblyNeutral] also?

**Comment by BrennanConroy** [comment]
Oh, you did that in another PR already, never mind

**Comment by bricelam** [comment]
(This depends on aspnet/EntityFramework#1682)

**Comment by davidfowl** [comment]
Any reason we need to do this?

**Pull request closed without merging**
