### PR TITLE
Add ConfigurationFilterLoggerSettings

### PR DESCRIPTION
**Pull request by andrewlock**
Add `ConfigurationFilterLoggerSettings` for `WithFilter` configuration
- Provides similar behaviour to `ConfigurationConsoleLoggerSettings`
- Add Extension method for `WithFilter`

Addresses #437

### CODE REVIEW

**Comment by andrewlock** [comment]
@muratg, was just wondering why this was closed unmerged, without comment?

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/Logging/issues/589

**Comment by muratg** [comment]
@andrewlock Apologies, I thought I added the comment, doing it this time :)

- https://github.com/aspnet/Logging/pull/576 contains changes to make filtering configuration more sane
- Per team triage, we decided to remove Microsoft.Extensions.Logging.Filter. https://github.com/aspnet/Logging/issues/589 

Thanks for the PR, though until recently https://github.com/aspnet/Logging/issues/437 was in the Backlog.

**Comment by andrewlock** [comment]
Fair enough, as long as the functionality gets there eventually, I'm happy :)

**Pull request closed without merging**
