### PR TITLE
Use RuntimeInformation for OS detection

### PR DESCRIPTION
**Pull request by BrennanConroy**
#279
@kichalla

### CODE REVIEW

**Comment by muratg** [comment]
I assume this is tested on CoreCLR and CLR.  :)

:shipit:

**Comment by kichalla** [comment]
I recently reverted the change made this in PR to resolve the issue https://github.com/aspnet/Logging/issues/311

**Comment by BrennanConroy** [comment]
Ah, that's no good. Should we close the issue then?

**Comment by davidfowl** [comment]
@kichalla Did you report the bug?

**Pull request closed without merging**
