### PR TITLE
Add Microsoft.Extensions.Logging.AzureWebAppDiagnostics to NuGetPackageVerifier.json

### PR DESCRIPTION
**Pull request by pakrym**
@Tratcher

### CODE REVIEW

**Comment by Tratcher** [comment]
:shipit:

**Comment by muratg** [comment]
Per @pranavkm, this is not required, as standard checks apply to all packages. Only if you need to have some exceptions or something, you can ignore this file when you have a new package.

I recommend closing this PR without merging.

**Comment by Tratcher** [comment]
When did this change? And why do we still get CI warnings about missing packages?

**Comment by muratg** [comment]
Not sure since when this is just a warning and not an error. @pranavkm is thinking about removing the warning.

**Pull request closed without merging**
